### ISSUE TITLE
Getting a 403 error while using "git push"

### ISSUE THREAD

**Issue by SuSSan143** [zero-to-mastery/start-here-guidelines#11948]
Why am I getting this error and how to fix it?

`ERROR: Permission to zero-to-mastery/start-here-guidelines.git denied to SuSSan143.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by sophiabrandt** [comment]
@SuSSan143 did you follow the guide/instructions and **forked** the repository?
https://github.com/zero-to-mastery/start-here-guidelines#a-guide-to-get-started

This error often occurs when students forget to fork the repository and try to push to the master repository (this one) - to which they don't have access.

You'll need to make your own "copy" of the repository by forking it.

If you have further questions, you can also ask in the Discord community in the #github channel.
