### ISSUE TITLE
CONFLICT PRESENT WHILE MERGING

### ISSUE THREAD

**Issue by codersneha** [zero-to-mastery/start-here-guidelines#12042]
EACH AND EVERY TIME MERGING CONFLICT IS EMERGING WHENEVER I AM TRYING TO  GIVE A PULL REQUEST
I HAVE TRIED 8  TIMES WITH DIFFERENT BRANCHES EACH TIME.
I AM IN A STALEMATE SITUATION. PLEASE HELP ME OUT AS SOON AS POSSIBLE.

WILL BE WAITING FOR A QUICK RESPONSE.

THANK YOU

**Comment by sophiabrandt** [comment]
Please follow the guide here: https://github.com/zero-to-mastery/start-here-guidelines#a-guide-to-get-started
You need to make sure to [sync your fork](https://short.pm/forksync).

I will close this now, feel free to reach out on Discord if you need more guidelines.
