### ISSUE TITLE
Request for contributing invitation.

### ISSUE THREAD

**Issue by duckstroms** [zero-to-mastery/start-here-guidelines#12342]
Hey, Myself Andri Wahyudi (1st Hackerone Inc Leaderboard)

- [ ]  Python Programming Enthusiast
- [ ]  Penentration Testing / Vulnerability Analysis
- [ ]  Focus on Contributing more throughout the year

**Comment by sophiabrandt** [comment]
This repository is a playground for the Zero To Mastery community, **you are free to contribute** by following the steps in the README.

Maintainer status is invitation only.
