### ISSUE TITLE
Entries in CONTRIBUTIONS.md needs text formatting

### ISSUE THREAD

**Issue by DonMarvex** [zero-to-mastery/start-here-guidelines#14324]
I went through the list of contributors in the CONTRIBUTIONS.md file and couldn't help but notice some deviations from the initial format used for making entries of usernames/links to profiles.

The required
```Markdown
-  [@Username](profile link)
``` 

Deviations
```Markdown
-[@Username](profile link). 
# No whitespace after the hyphen "-"

-[@Username] (profile link). 
# Whitespace between ] and (
```

Requesting for permission to make changes so all profile usernames/profile links follow the exact same format.

**Comment by manishbajagai2** [comment]
I would love to work on this issue. Would you please like to assign it to me

**Comment by DonMarvex** [comment]
> I would love to work on this issue. Would you please like to assign it to me

It has not been assigned yet. Still waiting on someone with write access to check the issues section

**Comment by manishbajagai2** [comment]
@DonMarvex Shall i perform the required formatting needed and make a pr request

**Comment by DonMarvex** [comment]
> @DonMarvex Shall i perform the required formatting needed and make a pr request

You can do so. I've tried to make a PR with the changes but it keeps failing the Push Back Formatted Code check.

**Comment by manishbajagai2** [comment]
ok sure will try out now

**Comment by DonMarvex** [comment]
Issue has been fixed. Thanks
