### ISSUE TITLE
Discord Link 

### ISSUE THREAD

**Issue by imlakshay08** [zero-to-mastery/start-here-guidelines#14605]
Do you have any discord server of zero to mastery. If yes, could you please provide link of it ?.

**Comment by Flo-git** [comment]
It's not free. It's $39 a month.:( Here's where tou can purchase your membership https://zerotomastery.io/community/developer-community-discord/
Cheers

**Comment by imlakshay08** [comment]
Okay. Thank you @Flo-git for providing the info.

**Comment by dev-sampsonorson** [comment]
@Flo-git Please, what do you get with the paid membership?

**Comment by sophiabrandt** [comment]
The Discord server is a private server _for students of ZTM_: that means you either have to

* buy an Udemy course by Andrei Nagoie (Zero to Mastery)

or

* get a membership to the Zero to Mastery Academy (see link above)
