### ISSUE TITLE
anything wrong with this code?

### ISSUE THREAD

**Issue by rrkoka** [zero-to-mastery/start-here-guidelines#15139]
arr = [1, 5, 2, 6, 3]

def find_duplicates_in_arrays(array1):
    sum_value = 10
    i = 0

    for i in range(len(array1)):
        complement = sum_value - array1[i] 
        if complement in range(i+1, len(array1)):
            return True

        else:
            i += 1
    return False

print(find_duplicates_in_arrays(arr))

**Comment by sophiabrandt** [comment]
If you have any coding questions, please ask them on the ZTM discord, Udemy FAQ, or a dedicated forum/site for coding help.
As your question is not related to this repository, I am closing this issue.
Good.luck.
