### ISSUE TITLE
Checkout PR problem

### ISSUE THREAD

**Issue by AbdifatahYasin1** [zero-to-mastery/start-here-guidelines#15814]
![Screenshot (109)](https://user-images.githubusercontent.com/41564330/175091065-31a204ab-3f4b-42ec-b96e-8e99095bedb2.png)

**Comment by donmarvex** [comment]
@AbdifatahYasin1 This has been happening for some time now. It seems only branches named `master` successfully pass this step, not certain about it. @kennithnichol , could you please check this out?

**Comment by AbdifatahYasin1** [comment]
I solved this problem thanks @donmarvex
