### ISSUE TITLE
Commit changes step doesn't run in run-sort-users-script workflow

### ISSUE THREAD

**Issue by donmarvex** [zero-to-mastery/start-here-guidelines#15873]
## Description
All other steps excluding this step in the Github actions workflow run for `run-sort-users-script.yml` as seen here in [run python sort script](https://github.com/zero-to-mastery/start-here-guidelines/runs/7075663669?check_suite_focus=true) doesn't run at all.

![image](https://user-images.githubusercontent.com/32850163/175979201-98e53003-93c9-4229-89b7-27e48dc677aa.png)

![image](https://user-images.githubusercontent.com/32850163/175978380-ba988a0c-c7d7-475c-b210-1fe8ebf03507.png)

## Effect
The sort method never gets run to sort new users added to the contributors list.
As seen below, after the changes made by @ZMonk91 , newer entries don't get sorted.
![image](https://user-images.githubusercontent.com/32850163/175980330-e32da173-eb14-47de-a127-6313d1ef2ab0.png)

Please could you check this out @kennithnichol

**Comment by sophiabrandt** [comment]
@donmarvex I see that you made changes to the workflow. Is this still a problem or can we close the issue?

**Comment by donmarvex** [comment]
> @donmarvex I see that you made changes to the workflow. Is this still a problem or can we close the issue?

It's still a problem. Firstly, the workflow doesn't get triggered sometimes on pull requests and when it runs, these 2 steps are not run at all.

**Comment by donmarvex** [comment]
@sophiabrandt  I mean, the purpose of the script is to automatically sort users anytime a pull request is made and then commit these changes made, but that step doesn't get run so any additions just go below the contributors file.

Also, the action doesn't always get triggered on every pull request.
