### ISSUE TITLE
Issue installing my URLparse on my Python using Linux virtual Machine

### ISSUE THREAD

**Issue by LouISoffcode** [zero-to-mastery/start-here-guidelines#16447]
I tried importing the urlparse using "import urlsparse" to "from urllib.parse import urlparse" in the nano rsf.py on my linux virtual machine but didn't work, I nano python3 but the file seems wrong

**Comment by sophiabrandt** [comment]
You don't need to install Python for making a pull request. Follow the README on how to contribute. That should suffice.

Thank you.
