### ISSUE TITLE
Invite me to join the organisation

### ISSUE THREAD

**Issue by ritikbanger** [zero-to-mastery/start-here-guidelines#17278]
Name: Ritik Banger

I am a Full Stack Javascript Engineer with robust problem-solving skills and proven experience in creating and designing web apps in a test driven environment and deploy them to cloud servers.

**Comment by EyuCoder** [comment]
Please make a pull request. The Zerobot will send you an invite link via email.

**Comment by Moein074** [comment]
i am a front end developer,what do you have to suggest?

**Comment by CBID2** [comment]
Can I be invited to the organization again @EyuCoder? I got kicked out for not having GitHub's two factor authentication feature enabled and I did it.
