### ISSUE TITLE
unavailable image file 

### ISSUE THREAD

**Issue by behappyleee** [zero-to-mastery/start-here-guidelines#17841]
cant see pull request image at 10 step on README.md file 
thanks for your effort :)

**Comment by Ayush-Dutt-Sharma** [comment]
@behappyleee claim

**Comment by Ayush-Dutt-Sharma** [comment]
@behappyleee also provide image url

**Comment by Harixomxsingh** [comment]
Hey there I could help with that, can you sure me Why your img URL is not working it says 404 page or I can add another img pull from the internet just tell me which image I add do you have any img URL because you old img link says 404

**Comment by adel3li** [comment]
> cant see pull request image at 10 step on README.md file thanks for your effort :)

does it work now?

**Comment by RashadC30** [comment]
cant see pull request image at 10 step on README.md file thanks for your effort :)

how do i resolve this?
