### ISSUE TITLE
Misguided image when attempting to make a pull request step in README.md

### ISSUE THREAD

**Issue by gsvidal** [zero-to-mastery/start-here-guidelines#18974]
The next image for making the pull request step in README.md at line 75 is somehow misguided:

![image](https://docs.github.com/assets/cb-87213/images/help/pull_requests/pull-request-review-edit-branch.png)

When I tried to make the pull request using this branches setup as a reference ( master <- mybranch ), I made a pull request to my own repo. So this would work for our own pull request, but that's not the use case of this guide.

Now I'm sure the image below, which you can find (and hopefully update in your README.md file) when attempting to create a pull request ( ztm repo: master <- my repo: mybranch), would work better:

![image](https://user-images.githubusercontent.com/69181178/224470064-34d79e36-37c2-43b0-9f6f-ab38fb5513d2.png)

**Comment by ArslanYM** [comment]
Can I fix this issue?
