### ISSUE TITLE
Push and Pull Issues

### ISSUE THREAD

**Issue by TheCarGuru** [zero-to-mastery/start-here-guidelines#20337]
I pushed my changes to the repository but I'm unable to make a pull request. I followed the guideline and even YouTube video numerous times. I used VSC on Windows. The compare and pull request button doesn't pop up. Please help.

**Comment by TheCarGuru** [comment]
@l-white 

I'm a bit confused as I received the following from the @zero-to-mastery-bot:

🥳 Congratulations 🎉
Congrats on making your first Pull Request in the Zero To Mastery Organization!
You have been sent an invitation to join the ZTM github organization, please check your emails for further details!

ZTM Profile Badge
If you'd like the ZTM Badge to show up on your profile, you will need to [follow this guide](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership)!

🙏 Thanks for your pull request @TheCarGuru, The team will now review and merge this request. In the mean time why not check out some of the other opensource projects available, contributions are greatly appreciated!

Some of the most popular are

[Student Resources](https://github.com/zero-to-mastery/resources)
[ZTM Job Board](https://github.com/zero-to-mastery/ZtM-Job-Board)
[Complete Web Developer Manual](https://github.com/zero-to-mastery/complete-web-developer-manual)

Does this mean that my PR was successful or do I have to do it all over again?

**Comment by l-white** [comment]
@TheCarGuru There was nothing with your commit, so I suggest following the abbreviated instructions I provided to try again.
