### ISSUE TITLE
Typo : 'Get' spelt as 'Git' in the About Section

### ISSUE THREAD

**Issue by devTejaSrinivas** [zero-to-mastery/start-here-guidelines#23085]
The description in the about section has "Let's Git " instead of "Let's Get" which is gramatically incorrect . Also the word is having a captial letter which is not needed . Collaborators with write persmission to the repo , please fix this.

👇👇👇

![image](https://github.com/user-attachments/assets/bdccf45b-0abd-46ce-bfc1-0d172500a5a8)

**Comment by shico231** [comment]
i added my name to the contributers list

**Comment by LaurelineP** [comment]
That is not an issue but just a wordplay
