### ISSUE TITLE
Pull requests comment tagging contributors without pull permission

### ISSUE THREAD

**Issue by tigerlight** [zero-to-mastery/start-here-guidelines#4712]
Maybe the README.md could post a note at the top of the page telling students doing a first Pull Request to look for someone who has executed a recent Pull Request on the commits page,

https://github.com/zero-to-mastery/start-here-guidelines/commits/master

RE:
The Web Developer course suggest students add their name to the contributor list as a first experience for collaboration. The course suggests referencing someone in the comments as a way of asking that person to execute the pull request. However, students can't tell who has pull request permission so they (myself included) pick someone on the contributor list. I recently added myself and now students are tagging me in comments.

**Comment by sophiabrandt** [comment]
@tigerlight That's a good idea. Why don't you make a pull request with the suggested changes and I will try to merge it.

The Management Team has recently added a few more ZTM members with permissions, because the community has grown so much. We will try to clean up the repositories.
