### ISSUE TITLE
Unable to see my name in contributors.md file

### ISSUE THREAD

**Issue by I-rk1413** [zero-to-mastery/start-here-guidelines#5506]
Even after I have made the pull request as instructed by Andrei sir in Zero to Mastery Course, my name has not been added.Although a invitation to join the organisation has come and I have joined it also

**Comment by Aiswarya2020** [comment]
I'm also facing the same issue, my name also has not been added to the list.

**Comment by eemanioui** [comment]
@Aiswarya2020 @I-rk1413 you need to wait for one of the moderators to approve your requests. currently, there are close to 300 people in the queue waiting to be added. just a little patience you'll be added eventually. 

Why not use this waiting to time to contribute to one of the open-source projects
