### ISSUE TITLE
not seeing my name on contributors list

### ISSUE THREAD

**Issue by mutebinuhu** [zero-to-mastery/start-here-guidelines#5852]
hi im unable to see my names on the contributors list

**Comment by belbiad44** [comment]
hi im not seeing my name on contributors list

**Comment by MattCSmith** [comment]
@mutebinuhu Ensure that you PR does not have a merge conflict, if it has a conflict we are unable to merge it in

**Comment by sophiabrandt** [comment]
I'm closing this, because all related information is contained inside the PR in question.
