### ISSUE TITLE
Merge CONTRIBUTORS.md.save

### ISSUE THREAD

**Issue by sophiabrandt** [zero-to-mastery/start-here-guidelines#6310]
It looks like a few people didn't commit to `CONTRIBUTORS.md` but to `CONTRIBUTORS.md.save`.
Should we merge the two files?
@MattCSmith @SamirJouni

**Comment by MattCSmith** [comment]
@sophiabrandt Yeah that would be ideal

**Comment by sophiabrandt** [comment]
I will wait until some of the ongoing pull requests are done, and then I will merge the duplicate file.
