### ISSUE TITLE
Should change file extension of CODE_OF_CONDUCT  .html to .md 

### ISSUE THREAD

**Issue by tgmarinho** [zero-to-mastery/start-here-guidelines#690]
Should change the file extension of CODE_OF_CONDUCT  .html to .md 

Page not found:
https://github.com/zero-to-mastery/start-here-guidelines/blob/master/CODE_OF_CONDUCT.md

Its happened when I clicked this link: https://www.udemy.com/the-complete-junior-to-senior-web-developer-roadmap/learn/v4/t/lecture/10340674?start=0

..... "community and no matter your experience, you can participate with any sort of contribution. Check out this and our [code of conduct](https://github.com/zero-to-mastery/start-here-guidelines/blob/master/CODE_OF_CONDUCT.md). "...

**Comment by DiscoverSquishy** [comment]
Hey @tgmarinho thanks for creating the issue!
I've fixed it and now **https://github.com/zero-to-mastery/start-here-guidelines/blob/master/CODE_OF_CONDUCT.md**.
Should work fine. 

Happy learning!
