### ISSUE TITLE
Duplicate pull request

### ISSUE THREAD

**Issue by mrsindelic** [zero-to-mastery/start-here-guidelines#8498]
Hi @MattCSmith,

When I create my first pull request  called "added my name to contributors list " #7386 i made mistake and caused "merge conflict" problem.Just want to report that i'm created a new repo and made another pull request.So,please delete this pull request bcs this is duplicate. Thank you

With regards,

**Comment by sophiabrandt** [comment]
I think this has been resolved some way or the other. Thanks for letting us know.
